name: train_trajectory_wo_sa_ursa_local
workspace: PI_Chalvatzaki
project: pointattention

max_restarts: 0

bind_mounts:
  - container_path: /pfss/mlde/mlde_ext
    host_path: /pfss/mlde/mlde_ext
    propagation: rprivate
    read_only: false
  - container_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki
    host_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki
  - container_path: /pfss/mlde/users/fh36jega
    host_path: /pfss/mlde/users/fh36jega
  - container_path: /shared
    host_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki/shared
  - container_path: /run/determined/workdir
    host_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki/home/fh36jega
  - container_path: /workspace/
    host_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki/home/fh36jega/3d_diffuser_actor
  - container_path: /workspace/data/Peract_packaged
    host_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki/home/fh36jega/data/Peract_packaged
  - container_path: /workspace/data/peract/instructions.pkl
    host_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki/home/fh36jega/data/peract/instructions.pkl
  - container_path: /pointattention
    host_path: /pfss/mlde/workspaces/mlde_wsp_PI_Chalvatzaki/home/fh36jega/pointattention

environment:
  environment_variables:
    - WANDB_API_KEY=8009cee998358d908f42c2fce77f1ee094836701
    - WANDB_PROJECT=3d_diffuser_actor_debug
  add_capabilities:
    - IPC_LOCK
  drop_capabilities: null
  force_pull_image: false
  image:
    cpu: oddtoddler400/3d_diffuser_actor:0.0.3
    cuda: oddtoddler400/3d_diffuser_actor:0.0.3

resources:
  devices:
    - container_path: /dev/infiniband/
      host_path: /dev/infiniband/
      mode: mrw
  resource_pool: 42_Compute
  slots_per_trial: 1 # # GPUs

entrypoint: exec bash -c "cd /workspace && source scripts/slurm/startup-hook.sh && bash scripts/train/train_trajectory_wo_sa_ursa_local.sh"

searcher:
    name: single
    metric: validation_loss
    max_length:
      epochs: 1